server:
  port: 1852
  address: 0.0.0.0

lavalink:
  server:
    password: "supersecure"
    sources:
      youtube: true
      soundcloud: true
      bandcamp: false
      twitch: false
      vimeo: false
      http: false
      local: false
      spotify: true
    bufferDurationMs: 400
    youtubeSearchEnabled: true
logging:
  level:
    root: INFO